language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
script:
 - pylint --rcfile=pylintrc metadata
 - coverage run --include='metadata/*' pacifica-test.py -v
 - codeclimate-test-reporter
